# Generated by Django 3.1.4 on 2021-02-14 17:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Please add Title', max_length=50)),
                ('description', models.TextField(default='Please add Description', max_length=200)),
                ('moreinfo', models.TextField(blank=True)),
                ('due', models.DateField(blank=True, default=datetime.datetime.now)),
                ('status', models.ForeignKey(default=5, on_delete=django.db.models.deletion.SET_DEFAULT, to='index.status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
