# Generated by Django 3.1.4 on 2021-02-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20210217_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['title']},
        ),
    ]
