# Generated by Django 3.1.4 on 2021-02-18 11:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0016_usermate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usermate',
            new_name='Notification',
        ),
    ]
