# Generated by Django 3.1.4 on 2021-02-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_notification_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
